### ISSUE TITLE
Error: java heap space

### ISSUE THREAD

**Issue by XYWang-coder** [waps101/AlbedoMM#1]
Hi,

I made this error while running ‘java -Xmx2g -cp assembly.jar faces.apps.AlbedoModelBuilder’. Since I don't understand the java code, I would like to ask how to solve this error.

Thank you.

-------------------------------------------------------------------------------------------------------------------------------------
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/media/xy-w/Data/GitHub/AlbedoMM/scala/model/assembly.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at scala.reflect.ManifestFactory$$anon$12.newArray(Manifest.scala:141)
	at scala.reflect.ManifestFactory$$anon$12.newArray(Manifest.scala:139)
	at breeze.linalg.DenseMatrix$mcD$sp.copy$mcD$sp(DenseMatrix.scala:235)
	at scalismo.faces.momo.PancakeDLRGP.basisMatrix(PancakeDLRGP.scala:110)
	at faces.lib.AlbedoMoMoIO$$anonfun$faces$lib$AlbedoMoMoIO$$writeStatisticalModel$1.apply$mcV$sp(AlbedoMoMoIO.scala:430)
	at faces.lib.AlbedoMoMoIO$$anonfun$faces$lib$AlbedoMoMoIO$$writeStatisticalModel$1.apply(AlbedoMoMoIO.scala:426)
	at faces.lib.AlbedoMoMoIO$$anonfun$faces$lib$AlbedoMoMoIO$$writeStatisticalModel$1.apply(AlbedoMoMoIO.scala:426)
	at scala.util.Try$.apply(Try.scala:192)
	at faces.lib.AlbedoMoMoIO$.faces$lib$AlbedoMoMoIO$$writeStatisticalModel(AlbedoMoMoIO.scala:426)
	at faces.lib.AlbedoMoMoIO$$anonfun$faces$lib$AlbedoMoMoIO$$writeAlbedoMoMoExpress$1.apply$mcV$sp(AlbedoMoMoIO.scala:233)
	at faces.lib.AlbedoMoMoIO$$anonfun$faces$lib$AlbedoMoMoIO$$writeAlbedoMoMoExpress$1.apply(AlbedoMoMoIO.scala:229)
	at faces.lib.AlbedoMoMoIO$$anonfun$faces$lib$AlbedoMoMoIO$$writeAlbedoMoMoExpress$1.apply(AlbedoMoMoIO.scala:229)
	at scala.util.Try$.apply(Try.scala:192)
	at faces.lib.AlbedoMoMoIO$.faces$lib$AlbedoMoMoIO$$writeAlbedoMoMoExpress(AlbedoMoMoIO.scala:229)
	at faces.lib.AlbedoMoMoIO$$anonfun$writeToHDF5$1.apply$mcV$sp(AlbedoMoMoIO.scala:176)
	at faces.lib.AlbedoMoMoIO$$anonfun$writeToHDF5$1.apply(AlbedoMoMoIO.scala:163)
	at faces.lib.AlbedoMoMoIO$$anonfun$writeToHDF5$1.apply(AlbedoMoMoIO.scala:163)
	at scala.util.Try$.apply(Try.scala:192)
	at faces.lib.AlbedoMoMoIO$.writeToHDF5(AlbedoMoMoIO.scala:163)
	at faces.lib.AlbedoMoMoIO$$anonfun$write$1$$anonfun$apply$mcV$sp$3.apply(AlbedoMoMoIO.scala:154)
	at faces.lib.AlbedoMoMoIO$$anonfun$write$1$$anonfun$apply$mcV$sp$3.apply(AlbedoMoMoIO.scala:153)
	at scalismo.faces.utils.ResourceManagement$.using(ResourceManagement.scala:51)
	at faces.lib.AlbedoMoMoIO$$anonfun$write$1.apply$mcV$sp(AlbedoMoMoIO.scala:153)
	at faces.lib.AlbedoMoMoIO$$anonfun$write$1.apply(AlbedoMoMoIO.scala:153)
	at faces.lib.AlbedoMoMoIO$$anonfun$write$1.apply(AlbedoMoMoIO.scala:153)
	at scala.util.Try$.apply(Try.scala:192)
	at faces.lib.AlbedoMoMoIO$.write(AlbedoMoMoIO.scala:152)
	at faces.apps.AlbedoModelBuilder$.delayedEndpoint$faces$apps$AlbedoModelBuilder$1(AlbedoModelBuilder.scala:28)
	at faces.apps.AlbedoModelBuilder$delayedInit$body.apply(AlbedoModelBuilder.scala:13)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)

**Comment by XYWang-coder** [comment]
Oh, I solved it. Thank you

**Comment by BernhardEgger** [comment]
Can you please describe how you solved it/ what the issue was?
That could help others running into the same problem

**Comment by XYWang-coder** [comment]
Oh yes. I just change the -Xmx2g into -Xmx5g.

**Comment by BernhardEgger** [comment]
Thank you - I added this to the readme
